### ISSUE TITLE
Question: adding dimensions

### ISSUE THREAD

**Issue by Draemonaurious** [CD4017BE/VerticallyStackedDimensions#14]
I just stumbled upon this mod and was very intrigued with it. I have had no trouble using it with the vanilla dims and the modded dims but when I add a custom dim in the stacked dimension menu in world creation it calls it undefined and when I open the world and try to enter the dim the blocks won't break and it won't let me inter the new dim. I've been looking for a tutorial for this and haven't been successful. Is there something else I need to do to the added dim before World creation to make it functional? This mod is pretty awesome and I would like to get this to work. I am simply trying to make another dim that is all stone with vanilla and modded gens. I left it at the max height of 255. Expected blocks are minecraft:stone and a transition of 16, Probably doesn't need to be that much but that's what I put on all the dims. I even made one and reduced the height to 144 and still didn't work. Please add a tutorial for this in the wiki or if their is one point my blindness in the right direction. Thank you for this wonderful mod.

**Comment by CD4017BE** [comment]
Currently the mod can't add new dimensions itself but that is a planned feature.

So the "add dimension" button in the menu does not actually create a new dimension. It's purpose currently is to manually add existing dimensions that are not automatically recognized by the mod. These are for example ones that are not defined until a world is actually created and loaded, like RF-Tools Worlds.

**Comment by CD4017BE** [comment]
Adding dimensions is now implemented and will be in next release:

1. Enter an unused dimension id to `add Dimension`.
2. Select it to the right list using `Select` button.
3. Click `Edit Dimension`
4. Change the bottom left button to `Create Dimension: Yes`. The dimension is now named `dimstack_custom` instead of `undefined`.
5. Click on the newly appeared `Dimension Creation` button to configure its properties.
6. Enter a biome name/id if you want a single biome instead of normal overworld biome generation.
7. The chunk generator `Empty World` is recommended for sky, void or mining dimensions. Use block layers and other generation features to fill them with stuff.

TODO: add some aesthetic configuration options for created dimensions like fog colors, sky colors, brightness, horizon and cloud height.
