### ISSUE TITLE
Incompatibility with Metamorph/Changeling

### ISSUE THREAD

**Issue by inkdear** [CD4017BE/VerticallyStackedDimensions#16]
Attempting to ascend from a lower dimension while transformed into a mob with a significantly lower view height than the player often results in the player being immediately teleported back into the lower dimension. A player with a one-block height (morphed into a silverfish, parrot, etc) will also teleport when standing on the lower of the two layers of purple bedrock/portal blocks, so I assume what is happening is that the player is being placed on a lower bedrock/portal block and instantly teleporting back to the lower dimension.

I assume this is a result of either how Changeling achieves its lowered player view height, or a result of Vertically Stacked Dimensions using the position of the player's view height (rather than their feet) to decide if they are low enough in the world to teleport to the lower dimension. I will be reporting this on Changeling's issue tracker as well.

Changeling is a new fork of Metamorph: https://www.curseforge.com/minecraft/mc-mods/changeling

**Comment by CD4017BE** [comment]
My teleport mechanism only orients itself on the upper and lower end of the player's (or entity's) bounding box. In order to get teleported again the player (or entity) would have to move back a distance at least equal to its height.
However it is possible that the meta morph mod does some position corrections to the player after the dimension change which moves it behind the threshold height. And in case of the silverfish morph the bounding box - and therefore the height error margin - becomes very small so that even minor movement glitches can be enough to trigger the teleport again.

**Comment by CD4017BE** [comment]
1e49d25a0c3099337e301640f562ee358d8e32d3 will probably fix this issue
