### ISSUE TITLE
[Feature Request] Config option to not mess with top of Nether

### ISSUE THREAD

**Issue by Zygus42** [CD4017BE/VerticallyStackedDimensions#18]
## The problem
I'm running mods which add biomes to the Nether.  While I can set your config options to put the Nether top back that your mod takes out, it rebuilds it as standard Nether, not with the Nether biomes.  I can set the height of nether to be 127, but then i lose half the nether.

## My solution
A setting that says "RemoveTopOfNether:true", so that I can set it to false.

## Why the existing features won't cut it
I can set your config options to put the Nether top back that your mod takes out, it rebuilds it as standard Nether, not with the Nether biomes.
I can set the height of nether to be 127, but then i lose half the nether.
I can't say "only remove bedrock layers at top and bottom and leave the rest alone".

**Comment by CD4017BE** [comment]
The mod does not remove the top Nether, I mean the Nether is already only 128 Blocks in vanilla MC high without this mod.
If by "remove the top Nether" you mean that previous versions of this mod added it by default and the current version doesn't, well the feature wasn't removed it only became optional, non default and more tweakable.
But nothing should have changed that would affect biome generators: it still generates the top Nether terrain as early as possible to make sure it is already present when the biome generators run. _(otherwise I need to know in which version it worked and what mods you were using to generate the biomes)_

Your actual issue with other mods not generating their biome related stuff in the added top Nether is because their biome generator implementations simply don't modify blocks above 128, probably because the mod developers thought: `there are no blocks in that region anyway so better stop generating at Y=127 to save performance`.
So you need to ask them to change their code to make the biome generator run above 128 as well. In case of code that runs during chunk population they could even use `Chunk.getTopFilledSegment()` to keep the performance optimisation in case no top nether is present.

**Comment by Zygus42** [comment]
Ah, i see - i was under the impression that the nether was 255.  

Ok, will let them know.
