### ISSUE TITLE
Beign able to make CONSTANT config

### ISSUE THREAD

**Issue by Zack7292** [CD4017BE/VerticallyStackedDimensions#22]
## The problem
we can't make config that you don't have to set back up after already setting it up.

## My solution
making so you can simply save it as permanent and, every time you try to generate a world with this config (without touching the vertically stack section) will automatically regenerate the same as you had.
## Why the existing features won't cut it
this will add a way to modpack makers to use your mod freely so they can preset stack dimensions for their packs

**Comment by CD4017BE** [comment]
The dimension stack "default" settings are defined in the [mod's config script](https://github.com/CD4017BE/VerticallyStackedDimensions/wiki/General-Configuration), so if you use that instead of the in-game configuration GUI it will generate the same world every time. If you also want that config resist overrides by mod updates, set `VERSION = /0;`.

And when using the in-game configuration GUI you can use the `import settings` button to apply the settings of an existing world or any previously exported settings file.

As I understand your issue, what you probably want is to be able to set an in-game configured dimension stack to become default.
A implementation for this could look like this: Whenever the mod finds a `dimensionstack.dat` file in the `/config/cd4017be/` directory (where the mod's configuration script is in, too) it will ignore any settings in the config script related to world generation and apply that file as default preset for world generation instead (basically as if you had used `import settings` in the in-game configuration GUI).

So to make settings global you would either use `export settings` when you're done in the in-game configuration or copy the `dimensionstack.dat` file of a world save you're happy with over into the config directory. This should also make it easier to apply settings from single-player worlds onto a server. And for mod-pack deployment simply include the `dimensionstack.dat` file of the world you want to have together with all the other mod config files.

**Comment by Zack7292** [comment]
so in a sentence: export your .dat file, rename it dimensionstack.dat and remplce the normal one and that's it?
