### ISSUE TITLE
Error on Loading Game

### ISSUE THREAD

**Issue by TheDarkBadger** [CD4017BE/VerticallyStackedDimensions#25]
When creating the world everything is fine, no problems.
If i quit out, and then load the world again i crash almost instantly once the world has loaded with this error
java.lang.ArrayIndexOutOfBoundsException: -1

Mod List:
- CD4017BE Library	
- The Beneath
- The Erebus
- Vertically Stacked Dimensions

Only seems to happen when using the RCP file and having the add("basicLayer" lines in the RCP file.
When using the ingame editor instead of the RCP i have no issues

[ConfigAndError.zip](https://github.com/CD4017BE/VerticallyStackedDimensions/files/4080513/ConfigAndError.zip)

**Comment by CD4017BE** [comment]
Your height values were incorrect: the first two numbers in `[3, 0, 3, 5]#` would mean start noise at `y=3` with zero density, increase to full density towards `y=0` which is backwards representing a negative bottom noise layer thickness (my code just generated no blocks there). But when you quit and reloaded the game, the `-3` turned into a thickness of '253' due to 8-bit clipping in the save format so the generator crashed the game trying to generate blocks blow `y=0`.

I fixed it so it wouldn't crash anymore but you should still change your heights to `[0, 0, 3, 5]#` (solid 0 to 3, fade out to 5) or `[0, 3, 3, 5]#` (fade in from 0 to 3, fade out to 5).
