### ISSUE TITLE
Feature: Retroactive Worldgen for portals

### ISSUE THREAD

**Issue by aevumdefluo** [CD4017BE/VerticallyStackedDimensions#28]
If I add this to an existing world will it generate portals? If not, is there a way to do so?

Sorry to ask here as I couldn't figure out where else as I cannot use twitch to login to curse to ask. I really need to know as this absolute gem of a mod would be amazing to have in my server. Thank you for your time and this mod.

**Comment by CD4017BE** [comment]
First of all you need to design the dimension stack you want to have on the server world. You can do this in singleplayer using either the config file or the Dimensionstack configuration menu ingame when creating a new world (or both). Then create a new singleplayer world to test if it gives you what you wanted. After that you can copy the `dimensionstack.dat` file from your created singleplayer world save over to the server world save and install the mod on the server (also copy the config file if you did any changes to it).

However with an existing world you have the problem, that it would only add portals to newly generated chunks as there is currently no retroactive worldgen (yet). Only exception are ceiling portals in top open dimensions which are generated on demand as soon you're building stuff close to the world ceiling. _So if you're for example just adding a void dimension above the overworld then it's no issue._

If necessary you could generate missing portals manually via
`/fill ~-128 0 ~-64 ~127 0 ~63 dimstack:portal` for the floor and with the portal ceiling height instead of 0 for the ceiling. The given x, z coordinates will do a 256x128 area and max out the usual 32768 block limit per command. So you might need multiple passes or do it only in regions that players want to have it.

Maybe also do `/fill ~-64 1 ~-64 ~63 4 ~63 minecraft:stone replace minecraft:bedrock` or similar if there is bedrock blocking the way to the portals.
